<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE school [
	<!ELEMENT school (fpt, vin) >
	<!ELEMENT fpt (class*) >
	<!ELEMENT vin (class*) >
	<!ELEMENT class (student*) >
	<!ELEMENT student (id, name, phone, address) >
	<!ELEMENT id (#PCDATA) >
	<!ELEMENT name (#PCDATA) >
	<!ELEMENT phone (#PCDATA) >
	<!ELEMENT address (#PCDATA) >
	
	<!ATTLIST school address CDATA #IMPLIED>
	<!ATTLIST class name CDATA #IMPLIED>
]>
<?xml-stylesheet type="text/xsl" href="class.xsl"?>
<school address="x" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<fpt>	
		<class name="T1807E">
			<student>
				<id>1</id>
				<name>1</name>
				<phone>1</phone>
				<address>1</address>
			</student>
			<student>
				<id>2</id>
				<name>2</name>
				<phone>2</phone>
				<address>2</address>
			</student>
		</class>
		<class name="T1809E">
			<student>
				<id>3</id>
				<name>3</name>
				<phone>3</phone>
				<address>3</address>
			</student>
		</class>
	</fpt>
	<vin>	
		<class name="T1806E">
			<student>
				<id>4</id>
				<name>4</name>
				<phone>4</phone>
				<address>4</address>
			</student>
			<student>
				<id></id>
				<name></name>
				<phone></phone>
				<address></address>
			</student>
		</class>
		<class name="T1808E">
			<student>
				<id></id>
				<name></name>
				<phone></phone>
				<address></address>
			</student>
		</class>
	</vin>
</school>