<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document [
	<!ELEMENT document (category*) >
	<!ELEMENT category (name, description, logo, list_post) >
	<!ELEMENT list_post (post*) >
	<!ELEMENT post (title, content, description, image, createdate, tag) >
	
	<!ELEMENT name (#PCDATA) >
	<!ELEMENT description (#PCDATA|x) >
	<!ELEMENT logo (#PCDATA) >
	<!ELEMENT title (#PCDATA) >
	<!ELEMENT content (#PCDATA) >
	<!ELEMENT image (#PCDATA) >
	<!ELEMENT createdate (#PCDATA) >
	<!ELEMENT tag (#PCDATA) >
	<!ELEMENT x (#PCDATA) >
]>
<document>	
	<category>
		<name> category 1</name>
		<description>dsdsdsd</description>
		<logo></logo>
		<list_post>
			<post>
				<title> post 1</title>
				<content></content>
				<description>
					<x>Ä‘asdsdsd</x>
				</description>
				<image></image>
				<createdate></createdate>
				<tag></tag>
			</post>
			<post>
				<title> post 2</title>
				<content></content>
				<description></description>
				<image></image>
				<createdate></createdate>
				<tag></tag>
			</post>
			<post>
				<title> post 3</title>
				<content></content>
				<description></description>
				<image></image>
				<createdate></createdate>
				<tag></tag>
			</post>
		</list_post>
	</category>
	<category>
		<name> category 2</name>
		<description></description>
		<logo></logo>
		<list_post>
			<post>
				<title> post 1</title>
				<content></content>
				<description></description>
				<image></image>
				<createdate></createdate>
				<tag></tag>
			</post>
			<post>
				<title> post 4</title>
				<content></content>
				<description></description>
				<image></image>
				<createdate></createdate>
				<tag></tag>
			</post>
			<post>
				<title> post 5</title>
				<content></content>
				<description></description>
				<image></image>
				<createdate></createdate>
				<tag></tag>
			</post>
		</list_post>
	</category>
</document>
