=== bbangchiuu/phptranning/www/testxml/d15m5/BookSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.BookCatalog.com"
            xmlns="http://www.BookCatalog.com"
            elementFormDefault="qualified">

        <xs:element name="Author" type="xs:string" />
        <xs:element name="Title" type="xs:string" />
        <xs:element name="Genre" type="xs:string" />
        <xs:element name="Price" type="xs:string" />
        <xs:element name="Publish" type="xs:string" />
        <xs:element name="Description" type="xs:string" />

        <xs:element name="Book">
            <xs:complexType>
                <xs:sequence>
                    <xs:element ref="Author"/>
                    <xs:element ref="Title"/>
                    <xs:element ref="Genre"/>
                    <xs:element ref="Price"/>
                    <xs:element ref="Publish"/>
                    <xs:element ref="Description"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

        <xs:element name="Catalog">
            <xs:complexType>
                <xs:sequence>
                    <xs:element ref="Book" min0ccurs="1" max0ccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
</xs:schema>

=== bbangchiuu/phptranning/www/testxml/d15m5/Book.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Sample.xsl" ?>
<Catalog xmlns="http://www.BookCatalog.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.BookCatalog.com BookSchema.xsd">

        <Book>
            <Author>Gamabardella, Matthew</Author>
            <Title>XML DEvelop</Title>
            <Genre>Computer</Genre>
            <Price>44</Price>
            <Publish>2000-10-01</Publish>
            <Description>An in....</Description>
        </Book>
</Catalog>
